apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: debug
      image: nicolaka/netshoot
      command: [ "sleep", "infinity" ]
      stdin: true
      tty: true
  restartPolicy: Never
